from dataclasses import dataclass


class ErrorCode:
    OK = "OK"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_REFRESH_INVALID = "AUTH_REFRESH_INVALID"
    AUTH_USERNAME_TAKEN = "AUTH_USERNAME_TAKEN"
    FORBIDDEN = "FORBIDDEN"
    TRADE_DECLARATION_NOT_FOUND = "TRADE_DECLARATION_NOT_FOUND"
    RECONCILE_TASK_NOT_FOUND = "RECONCILE_TASK_NOT_FOUND"
    RULE_NOT_FOUND = "RULE_NOT_FOUND"
    RULE_VALIDATION_ERROR = "RULE_VALIDATION_ERROR"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
    INTEGRATION_NOT_CONFIGURED = "INTEGRATION_NOT_CONFIGURED"
    INTEGRATION_UPSTREAM_ERROR = "INTEGRATION_UPSTREAM_ERROR"


@dataclass
class AppException(Exception):
    code: str
    message: str
    status_code: int = 400
